# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a88c53755557f0f9c989b6aa5c154396800110797f3aef13c60a0bac26ff807a61ea35cab38c993c3bedf30b4169526e14b05e2719540f3cd1cb6ee4a086abe9

test:
  secret_key_base: 448985ccec4d2d44293dde4ee7a77590ab2c898f62c392aa9cf835a61a18468cb7478898d3e7694b8eacb0a70ef070d034605c53453b4c66540de73a25c4290a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
